// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArKI9CO5llksF76LC1Bgi4IblwnhURLOQ',
    appId: '1:1033255788496:android:cb596c760e95123f6f63d5',
    messagingSenderId: '1033255788496',
    projectId: 'clinic-app-86bcf',
    storageBucket: 'clinic-app-86bcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKrOCqpxr9jtuX0QQLj1gLPzn2SVMCWbk',
    appId: '1:1033255788496:ios:39f58f69624fe39c6f63d5',
    messagingSenderId: '1033255788496',
    projectId: 'clinic-app-86bcf',
    storageBucket: 'clinic-app-86bcf.firebasestorage.app',
    iosClientId: '1033255788496-k2p4lap9herrfl9cpu786q5bele0s0ei.apps.googleusercontent.com',
    iosBundleId: 'com.wellness.vendor',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhEAKCQiMqYuhof0tJiyIkAwELtxHCn5E',
    appId: '1:1033255788496:web:f1e2468e3bb308b16f63d5',
    messagingSenderId: '1033255788496',
    projectId: 'clinic-app-86bcf',
    authDomain: 'clinic-app-86bcf.firebaseapp.com',
    storageBucket: 'clinic-app-86bcf.firebasestorage.app',
    measurementId: 'G-0MR0CSHDST',
  );

}